# Generated by Django 2.1 on 2019-05-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_real', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='net_sale2',
            field=models.BooleanField(default=None, verbose_name='Чистая продажа'),
        ),
    ]
