# Generated by Django 2.1 on 2019-05-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_real', '0002_flat_net_sale2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='net_sale2',
            field=models.BooleanField(null=True, verbose_name='Чистая продажа'),
        ),
    ]
