# Generated by Django 2.1 on 2019-05-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_real', '0004_remove_flat_net_sale2'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='izn_ztd',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Остаток ЗТД'),
        ),
    ]
